package com.alianga.jkit.sql.schema.model;

import com.alianga.jkit.sql.ast.SqlExpr;

/**
 * 列级约束。Java 8 无 sealed，用 {@link Kind} 做穷尽分支；新增约束必须加枚举值。
 *
 * @author 郑明亮
 * @since 2.0.1
 */
public interface ColumnConstraint {
    /**
     * 约束种类，formatter / rewriter 按此 switch。
     */
    enum Kind {
        NOT_NULL,
        NULLABLE,
        DEFAULT_VALUE,
        AUTO_INCREMENT,
        INLINE_PRIMARY_KEY,
        INLINE_UNIQUE,
        COMMENT,
        ON_UPDATE,
        CHARACTER_SET,
        COLLATION
    }

    /**
     * @return 约束种类
     */
    Kind kind();

    /**
     * {@code NOT NULL}。
     */
    final class NotNull implements ColumnConstraint {
        /** 单例。 */
        public static final NotNull INSTANCE = new NotNull();

        private NotNull() {
        }

        /**
         * {@inheritDoc}
         */
        @Override
        public Kind kind() {
            return Kind.NOT_NULL;
        }
    }

    /**
     * 显式 {@code NULL}。
     */
    final class Nullable implements ColumnConstraint {
        /** 单例。 */
        public static final Nullable INSTANCE = new Nullable();

        private Nullable() {
        }

        /**
         * {@inheritDoc}
         */
        @Override
        public Kind kind() {
            return Kind.NULLABLE;
        }
    }

    /**
     * {@code DEFAULT expr}。
     */
    final class DefaultValue implements ColumnConstraint {
        private final SqlExpr expr;
        private final String rawText;

        /**
         * @param expr 默认值表达式，可空（解析失败时仅保留原文）
         * @param rawText 原文
         */
        public DefaultValue(SqlExpr expr, String rawText) {
            this.expr = expr;
            this.rawText = rawText == null ? "" : rawText;
        }

        /**
         * {@inheritDoc}
         */
        @Override
        public Kind kind() {
            return Kind.DEFAULT_VALUE;
        }

        /**
         * @return 默认值表达式，可空
         */
        public SqlExpr expr() {
            return expr;
        }

        /**
         * @return 原文
         */
        public String rawText() {
            return rawText;
        }
    }

    /**
     * 自增：{@code AUTO_INCREMENT} / {@code IDENTITY} / {@code GENERATED … AS IDENTITY} / {@code SERIAL}。
     */
    final class AutoIncrement implements ColumnConstraint {
        /**
         * 自增形态。
         */
        public enum IdentityMode {
            /** {@code AUTO_INCREMENT} / 无 GENERATED 的 {@code IDENTITY} / {@code SERIAL}。 */
            UNSPECIFIED,
            /** {@code GENERATED ALWAYS AS IDENTITY}。 */
            ALWAYS,
            /** {@code GENERATED BY DEFAULT AS IDENTITY}。 */
            BY_DEFAULT
        }

        private final IdentityMode mode;
        private final Integer seed;
        private final Integer increment;

        /**
         * 无种子/步长的自增。
         *
         * @param mode 形态
         */
        public AutoIncrement(IdentityMode mode) {
            this(mode, null, null);
        }

        /**
         * @param mode 形态
         * @param seed 种子，可空
         * @param increment 步长，可空
         */
        public AutoIncrement(IdentityMode mode, Integer seed, Integer increment) {
            this.mode = mode == null ? IdentityMode.UNSPECIFIED : mode;
            this.seed = seed;
            this.increment = increment;
        }

        /**
         * {@inheritDoc}
         */
        @Override
        public Kind kind() {
            return Kind.AUTO_INCREMENT;
        }

        /**
         * @return 形态
         */
        public IdentityMode mode() {
            return mode;
        }

        /**
         * @return 种子，可空
         */
        public Integer seed() {
            return seed;
        }

        /**
         * @return 步长，可空
         */
        public Integer increment() {
            return increment;
        }
    }

    /**
     * 列内联 {@code PRIMARY KEY}。
     */
    final class InlinePrimaryKey implements ColumnConstraint {
        /** 单例。 */
        public static final InlinePrimaryKey INSTANCE = new InlinePrimaryKey();

        private InlinePrimaryKey() {
        }

        /**
         * {@inheritDoc}
         */
        @Override
        public Kind kind() {
            return Kind.INLINE_PRIMARY_KEY;
        }
    }

    /**
     * 列内联 {@code UNIQUE}。
     */
    final class InlineUnique implements ColumnConstraint {
        /** 单例。 */
        public static final InlineUnique INSTANCE = new InlineUnique();

        private InlineUnique() {
        }

        /**
         * {@inheritDoc}
         */
        @Override
        public Kind kind() {
            return Kind.INLINE_UNIQUE;
        }
    }

    /**
     * 列注释。
     */
    final class Comment implements ColumnConstraint {
        private final String text;

        /**
         * @param text 注释原文（已去掉包围引号）
         */
        public Comment(String text) {
            this.text = text == null ? "" : text;
        }

        /**
         * {@inheritDoc}
         */
        @Override
        public Kind kind() {
            return Kind.COMMENT;
        }

        /**
         * @return 注释文本
         */
        public String text() {
            return text;
        }
    }

    /**
     * MySQL {@code ON UPDATE expr}。
     */
    final class OnUpdate implements ColumnConstraint {
        private final SqlExpr expr;
        private final String rawText;

        /**
         * @param expr 表达式，可空
         * @param rawText 原文
         */
        public OnUpdate(SqlExpr expr, String rawText) {
            this.expr = expr;
            this.rawText = rawText == null ? "" : rawText;
        }

        /**
         * {@inheritDoc}
         */
        @Override
        public Kind kind() {
            return Kind.ON_UPDATE;
        }

        /**
         * @return 表达式，可空
         */
        public SqlExpr expr() {
            return expr;
        }

        /**
         * @return 原文
         */
        public String rawText() {
            return rawText;
        }
    }

    /**
     * {@code CHARACTER SET} / {@code CHARSET}。
     */
    final class CharacterSet implements ColumnConstraint {
        private final String charset;

        /**
         * @param charset 字符集名
         */
        public CharacterSet(String charset) {
            this.charset = charset == null ? "" : charset;
        }

        /**
         * {@inheritDoc}
         */
        @Override
        public Kind kind() {
            return Kind.CHARACTER_SET;
        }

        /**
         * @return 字符集名
         */
        public String charset() {
            return charset;
        }
    }

    /**
     * {@code COLLATE}。
     */
    final class Collation implements ColumnConstraint {
        private final String collation;

        /**
         * @param collation 排序规则名
         */
        public Collation(String collation) {
            this.collation = collation == null ? "" : collation;
        }

        /**
         * {@inheritDoc}
         */
        @Override
        public Kind kind() {
            return Kind.COLLATION;
        }

        /**
         * @return 排序规则名
         */
        public String collation() {
            return collation;
        }
    }
}
